version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: blog-app
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_USER: blog-app
      POSTGRES_PASSWORD: password

volumes:
  postgres_data:
